name: csem

channels:
  - conda-forge
  - gimli
dependencies:
  - "libblas=*=*mkl"
  - custem
  - discretize>=0.5.1
  - emg3d
  - empymod
  - h5netcdf
  - ipython
  - jupyter
  - matplotlib
  - memory_profiler
  - mkl
  - pymatsolver
  - python>=3.7
  - scooby
  - segyio
  - simpeg
  - xarray
